code-snippet/accordion/accordion-cs1/index.js, treeview/ej2-javascript-treeview-toc.html, treeview/ej2-typescript-treeview-toc.html
=> documentation(EJ2-71942): spacing issue resolved

ej2-javascript/ribbon/js/tabs-groups.md
=> documentation(71942): Fixed automation break

ej2-javascript/code-snippet/ribbon/classic-cs1/systemjs.config.js, ej2-javascript/code-snippet/ribbon/custom-header-cs1/systemjs.config.js, ej2-javascript/code-snippet/ribbon/file-submenu-cs1/systemjs.config.js, ej2-javascript/code-snippet/ribbon/filemenu-cs1/systemjs.config.js, ej2-javascript/code-snippet/ribbon/groups-cs1/systemjs.config.js, ej2-javascript/code-snippet/ribbon/items-cs1/systemjs.config.js, ej2-javascript/code-snippet/ribbon/minimize-cs1/systemjs.config.js, ej2-javascript/code-snippet/ribbon/simplified-cs1/systemjs.config.js, ej2-javascript/code-snippet/ribbon/tabs-cs1/systemjs.config.js, ej2-javascript/code-snippet/ribbon/tabs-cs2/systemjs.config.js, ej2-javascript/code-snippet/ribbon/visibility-cs1/systemjs.config.js
=> documentation(71942): Fixed sample issue

ej2-javascript/ribbon/ej2-javascript-ribbon-toc.html, ej2-javascript/ribbon/ej2-typescript-ribbon-toc.html, ej2-javascript/ribbon/js/events.md, ej2-javascript/ribbon/js/file-menu.md, ej2-javascript/ribbon/js/layouts.md, ej2-javascript/ribbon/ts/events.md, ej2-javascript/ribbon/ts/file-menu.md, ej2-javascript/ribbon/ts/getting-started.md, ej2-javascript/ribbon/ts/layouts.md
Ribbon topics order rearranged
=> documenatation(EJ2-822854): ribbon topics order rearranged

ej2-javascript/code-snippet/ribbon/classic-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/classic-cs1/ts/index.html, ej2-javascript/code-snippet/ribbon/custom-header-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/custom-header-cs1/ts/index.html, ej2-javascript/code-snippet/ribbon/file-submenu-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/file-submenu-cs1/ts/index.html, ej2-javascript/code-snippet/ribbon/filemenu-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/filemenu-cs1/ts/index.html, ej2-javascript/code-snippet/ribbon/getting-started-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/getting-started-cs1/ts/index.html, ej2-javascript/code-snippet/ribbon/groups-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/groups-cs1/ts/index.html, ej2-javascript/code-snippet/ribbon/items-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/minimize-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/minimize-cs1/ts/index.html, ej2-javascript/code-snippet/ribbon/simplified-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/simplified-cs1/ts/index.html, ej2-javascript/code-snippet/ribbon/tabs-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/tabs-cs1/ts/index.html, ej2-javascript/code-snippet/ribbon/tabs-cs2/ts/index.html, ej2-javascript/code-snippet/ribbon/visibility-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/visibility-cs1/ts/index.html
Need to resolve issues in UG documentation for Ribbon.
Updated and resolved issues in UG documentation for Ribbon.
**Before**
**After**
None (New Component)
NA
NA
* Is there any API name change? No.
* Did you record this case in the unit test or UI test? Yes
=> documentation(EJ2-824938): ribbon docs updated

ej2-javascript/menu/how-to/change-animation-settings.md, ej2-javascript/menu/how-to/customize-menu-using-events.md, ej2-javascript/sidebar/index.md, ej2-javascript/tab/how-to/create-wizard-using-tab.md, ej2-javascript/toolbar/item-configuration.md, ej2-javascript/toolbar/responsive-mode.md, ej2-javascript/toolbar/ts/getting-started.md, ej2-javascript/treeview/ts/getting-started.md
=> documentation(832446): fixed the broken link issue

ej2-javascript/carousel/animations-and-transitions.md, ej2-javascript/code-snippet/carousel/swipe-cs1/index.js, ej2-javascript/code-snippet/carousel/swipe-cs1/index.ts, ej2-javascript/code-snippet/carousel/swipe-cs1/js/index.html, ej2-javascript/code-snippet/carousel/swipe-cs1/styles.css, ej2-javascript/code-snippet/carousel/swipe-cs1/systemjs.config.js, ej2-javascript/code-snippet/carousel/swipe-cs1/ts/index.html
Documentation content for the swipeMode, api has been drafted.
=> documentation(ES-378253): content drafted for the swipe mode ug doc

ej2-javascript/code-snippet/accordion/accordion-cs4/index.js, ej2-javascript/code-snippet/accordion/accordion-cs4/index.ts, ej2-javascript/code-snippet/carousel/default-cs1/index.js, ej2-javascript/code-snippet/carousel/default-cs14/index.js, ej2-javascript/code-snippet/tab/tab-cs2/index.js, ej2-javascript/code-snippet/tab/tab-cs2/index.ts
Description:
Fix the script errors in javascript and typescript platfotm for tab, carousel and accordion component documentation
Areas affected and ensured:
Test cases:
NA
Test bed sample location:
NA
Additional checklist
=> documentation(SC-835216-Script): Fix the script errors in navigation docs

ej2-javascript/code-snippet/accordion/accordion-cs4/index.js, ej2-javascript/code-snippet/accordion/accordion-cs4/index.ts, ej2-javascript/code-snippet/tab/tab-cs2/index.js, ej2-javascript/code-snippet/tab/tab-cs2/index.ts
Description:
Resolve crossDomain error in accordion and tab
Areas affected and ensured:
Test cases:
NA
Test bed sample location:
NA
Additional checklist
=> documentation(ES-838844-Review): resolve crossdomain error.

ej2-javascript/menu/data-source-binding-and-custom-menu-items.md, ej2-javascript/sidebar/index.md
Resolved broken links issue for navigation repository
=> bug(839526): Resolved broken link issue for Navigation repository

ej2-javascript/appbar/js/es5-getting-started.md
Hi @Girija-Rajendran,
Please review the changes made in the md file.
Regards,
Scholar.
=> SEO-123334-JavaScript-AppBar

ej2-javascript/ribbon/ej2-typescript-ribbon-toc.html
Configured the ribbon file path in typescript TOC
=> sample(EJ2): Ribbon UG file path modified

ej2-javascript/menu/data-source-binding-and-custom-menu-items.md, ej2-javascript/sidebar/index.md
Resolved the broken links issues in navigation repository.
Resolved the broken links in Menu and sidebar component
NA
No area is affected due to this changes.
NA
NA
* Is there any API name change? No
* Did you record this case in the unit test or UI test? NA
=> bug(839526): Resolved broken link for Navigation repository

ej2-javascript/code-snippet/accordion/accordion-cs4/index.js, ej2-javascript/code-snippet/accordion/accordion-cs4/index.ts, ej2-javascript/code-snippet/tab/tab-cs2/index.js, ej2-javascript/code-snippet/tab/tab-cs2/index.ts
Description:
Fix the script errors in javascript and typescript platform for tab and accordion component documentation
Areas affected and ensured:
Test cases:
NA
Test bed sample location:
NA
Additional checklist
=> documentation(ES-827018-ResolveAdoptor): Resolve errors.

ej2-javascript/code-snippet/ribbon/HelpPaneTemplate/index.js, ej2-javascript/code-snippet/ribbon/HelpPaneTemplate/index.ts, ej2-javascript/code-snippet/ribbon/HelpPaneTemplate/styles.css, ej2-javascript/code-snippet/ribbon/custom-tooltip-cs1/index.js, ej2-javascript/code-snippet/ribbon/custom-tooltip-cs1/index.ts, ej2-javascript/code-snippet/ribbon/custom-tooltip-cs1/js/index.html, ej2-javascript/code-snippet/ribbon/custom-tooltip-cs1/styles.css, ej2-javascript/code-snippet/ribbon/custom-tooltip-cs1/systemjs.config.js, ej2-javascript/code-snippet/ribbon/custom-tooltip-cs1/ts/index.html, ej2-javascript/ribbon/ej2-typescript-ribbon-toc.html, ej2-javascript/ribbon/js/es5-getting-started.md, ej2-javascript/ribbon/js/events.md, ej2-javascript/ribbon/js/file-menu.md, ej2-javascript/ribbon/js/help-pane-template.md, ej2-javascript/ribbon/js/items.md, ej2-javascript/ribbon/js/layouts.md, ej2-javascript/ribbon/js/resizing.md, ej2-javascript/ribbon/js/tabs-groups.md, ej2-javascript/ribbon/js/tooltip.md, ej2-javascript/ribbon/ts/events.md, ej2-javascript/ribbon/ts/file-menu.md, ej2-javascript/ribbon/ts/getting-started.md, ej2-javascript/ribbon/ts/help-pane-template.md, ej2-javascript/ribbon/ts/items.md, ej2-javascript/ribbon/ts/layouts.md, ej2-javascript/ribbon/ts/resizing.md, ej2-javascript/ribbon/ts/tabs-groups.md, ej2-javascript/ribbon/ts/tooltip.md
Ribbon Ug topics moved to latest hotfix
=> docs(Ej2): Ribbon UG changes updated

ej2-javascript/code-snippet/appbar/prominent-cs1/styles.css
**Description:**
Resolved image not displayed issue in Prominent AppBar typescript and javascript preview sample documentation
**Areas affected and ensured:**
**Test cases:**
NA
**Test bed sample location:**
NA
**Additional checklist**
=> Documentation(ES-819678): Resolved image not displayed issue in Prominent AppBar typescript and javascript preview sample

ej2-javascript/sidebar/js/getting-started.md, ej2-javascript/sidebar/ts/getting-started.md
I have added a note "How to apply the proper backdrop for the Sidebar main content " section in the Sidebar documentation.
=> documentation(ES-842915): Need to add a note "How to apply the proper backdrop for the Sidebar main content " section in the Sidebar documentation.

ej2-javascript/sidebar/style.md
I have added the style "Prevent the animation transition" for the Sidebar component.
=> documentation(ES-844258): Need to add styles "Prevent the animation transition" for the Sidebar component.

ej2-javascript/code-snippet/ribbon/groupButtonIcon/index.js, ej2-javascript/code-snippet/ribbon/groupButtonIcon/index.ts, ej2-javascript/code-snippet/ribbon/groupButtonIcon/js/index.html, ej2-javascript/code-snippet/ribbon/groupButtonIcon/systemjs.config.js, ej2-javascript/code-snippet/ribbon/groupButtonIcon/ts/index.html, ej2-javascript/code-snippet/ribbon/groupButtonSelected/index.js, ej2-javascript/code-snippet/ribbon/groupButtonSelected/index.ts, ej2-javascript/code-snippet/ribbon/groupButtonSelected/js/index.html, ej2-javascript/code-snippet/ribbon/groupButtonSelected/systemjs.config.js, ej2-javascript/code-snippet/ribbon/groupButtonSelected/ts/index.html, ej2-javascript/code-snippet/ribbon/multipleSelection/index.js, ej2-javascript/code-snippet/ribbon/multipleSelection/index.ts, ej2-javascript/code-snippet/ribbon/multipleSelection/js/index.html, ej2-javascript/code-snippet/ribbon/multipleSelection/systemjs.config.js, ej2-javascript/code-snippet/ribbon/multipleSelection/ts/index.html, ej2-javascript/code-snippet/ribbon/simplifiedModeGroupButton/index.js, ej2-javascript/code-snippet/ribbon/simplifiedModeGroupButton/index.ts, ej2-javascript/code-snippet/ribbon/simplifiedModeGroupButton/js/index.html, ej2-javascript/code-snippet/ribbon/simplifiedModeGroupButton/systemjs.config.js, ej2-javascript/code-snippet/ribbon/simplifiedModeGroupButton/ts/index.html, ej2-javascript/code-snippet/ribbon/singleSelection/index.js, ej2-javascript/code-snippet/ribbon/singleSelection/index.ts, ej2-javascript/code-snippet/ribbon/singleSelection/js/index.html, ej2-javascript/code-snippet/ribbon/singleSelection/systemjs.config.js, ej2-javascript/code-snippet/ribbon/singleSelection/ts/index.html, ej2-javascript/ribbon/js/events.md, ej2-javascript/ribbon/js/items.md, ej2-javascript/ribbon/ts/events.md, ej2-javascript/ribbon/ts/items.md, ej2-javascript/ribbon/ts/modules.md
Need to add below UG topics for Ribbon group button.
1.Single selection
2.Multiple selection
3.Content
4.Iconcss
5.Selected
6.Groupbutton in simplified mode
The above mentioned topics has been added for Ribbon group button UG documentation.
NA
None (New Component)
NA
NA
* Is there any API name change? NA.
* Did you record this case in the unit test or UI test? Yes
=> documentation(EJ2-846268): ribbon group button topics added.

ej2-javascript/ribbon/js/events.md, ej2-javascript/ribbon/js/items.md, ej2-javascript/ribbon/ts/events.md, ej2-javascript/ribbon/ts/items.md
Need to add api links for ribbon group button UG documentation.
Api links are added for ribbon group button UG documentation.
NA
None (New Component)
NA
NA
* Is there any API name change? NA.
* Did you record this case in the unit test or UI test? Yes
=> documentation(EJ2-846268): ribbon group button api links are added.

ej2-javascript/ribbon/js/backstage.md, ej2-javascript/ribbon/js/events.md, ej2-javascript/ribbon/ts/backstage.md, ej2-javascript/ribbon/ts/events.md
Need to add the API links for ribbon backstage documentation in TS and JS platform
Added the API links for ribbon backstage documentation in TS and JS platform
NA
None (New Component)
NA
NA
* Is there any API name change? NA.
* Did you record this case in the unit test or UI test? Yes
=> documentation(EJ2-846267): backstage documentation api links updated

ej2-javascript/tab/ej2-javascript-tab-toc.html, ej2-javascript/tab/ej2-typescript-tab-toc.html
Description:
Remove the unwanted how to topic section in javascript and typescript docs.
=> documentation(ES-826386-removeTopic): remove unwanted how to topic section in toc file

ej2-javascript/code-snippet/sidebar/animate-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/animate-cs2/systemjs.config.js, ej2-javascript/code-snippet/sidebar/animation-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/context-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/default-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/document-click-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/document-click-cs2/systemjs.config.js, ej2-javascript/code-snippet/sidebar/fixed-position-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/gestures-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/gestures-cs2/systemjs.config.js, ej2-javascript/code-snippet/sidebar/mobile-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/multiple-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/position-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/position-cs2/systemjs.config.js, ej2-javascript/code-snippet/sidebar/position-cs3/systemjs.config.js, ej2-javascript/code-snippet/sidebar/sidebar-default-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/sidebar-dock-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/sidebar-howTo-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/sidebar-howTo-cs2/systemjs.config.js, ej2-javascript/code-snippet/sidebar/sidebar-howTo-cs3/systemjs.config.js, ej2-javascript/code-snippet/sidebar/sidebar-list-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/sidebar-same-position-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/sidebar-treeview-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/top-bottom-positions-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/types-cs1/systemjs.config.js, ej2-javascript/code-snippet/sidebar/web-cs1/systemjs.config.js
JS/TS- Sidebar Resolve the documentation preview samples compilation issues.
=> config(ES-849254): JS/TS- Sidebar Resolve the documentation preview samples compilation issues.

ej2-javascript/code-snippet/accordion/accordion-custom-animation-cs1/systemjs.config.js, ej2-javascript/code-snippet/tab/active-tab-style-cs1/systemjs.config.js, ej2-javascript/code-snippet/tab/collapse-cs1/systemjs.config.js, ej2-javascript/code-snippet/tab/disable-tab-cs1/systemjs.config.js, ej2-javascript/code-snippet/tab/icon-position-cs1/systemjs.config.js, ej2-javascript/code-snippet/tab/locale-cs1/systemjs.config.js, ej2-javascript/code-snippet/tab/orientation-tab-cs1/systemjs.config.js, ej2-javascript/code-snippet/tab/tab-animation-cs1/systemjs.config.js, ej2-javascript/code-snippet/tab/tab-height-cs1/systemjs.config.js, ej2-javascript/code-snippet/tab/tab-selection-cs2/systemjs.config.js, ej2-javascript/code-snippet/tab/tab-style-cs1/systemjs.config.js, ej2-javascript/code-snippet/toolbar/toolbar-items-cs3/systemjs.config.js
Description:
Resolve compilation issue.
Solution:
Adding ej2 notification package in the system config json file.
=> documentation(ES-836547-resolveConfig): Resolve conflict in navigation docs.

ej2-javascript/code-snippet/tab/active-tab-style-cs1/index.css, ej2-javascript/code-snippet/tab/collapse-cs1/index.js, ej2-javascript/code-snippet/tab/collapse-cs1/index.ts
**Description:**
Cleared the preview sample issues for our tab samples in typescript and javascript platform
**Areas affected and ensured:**
**Test cases:**
NA
**Test bed sample location:**
NA
**Additional checklist**
=> documentation(ES-852376): Cleared the preview sample issues for our tab samples in typescript and javascript platform

ej2-javascript/treeview/how-to/accordion-tree.md, ej2-javascript/treeview/how-to/customize-the-expand-and-collapse-icons.md, ej2-javascript/treeview/how-to/customize-the-tree-nodes-based-on-levels.md, ej2-javascript/treeview/how-to/get-dynamic-icon.md, ej2-javascript/treeview/how-to/hover-multi-line-tree-node.md, ej2-javascript/treeview/how-to/remove-parent-checkbox.md, ej2-javascript/treeview/template.md
Need to add the missed CSS styles for Remove parent checkbox topic in the JS TreeView documentation.
=> documentation(ES-854110): Need to add the missed CSS styles for Remove parent checkbox topic in the JS TreeView documentation.

ej2-javascript/accordion/ts/getting-started.md, ej2-javascript/appbar/ts/getting-started.md, ej2-javascript/breadcrumb/ts/getting-started.md, ej2-javascript/carousel/ts/getting-started.md, ej2-javascript/context-menu/ts/getting-started.md, ej2-javascript/menu/ts/getting-started.md, ej2-javascript/ribbon/ts/getting-started.md, ej2-javascript/sidebar/ts/getting-started.md, ej2-javascript/tab/ts/getting-started.md, ej2-javascript/toolbar/ts/getting-started.md, ej2-javascript/treeview/ts/getting-started.md
Updated the getting-started page.
=> documentation(851984): Update the getting started.

ej2-javascript/appbar/ts/getting-started.md, ej2-javascript/tab/js/getting-started.md
Resolve the getting started issue in navigation documentation.
=> documentation(ES-853828-gettingStarted): Resolve getting started issues in ts and js navigation docs.

ej2-javascript/accordion/js/es5-getting-started.md, ej2-javascript/tab/js/es5-getting-started.md, ej2-javascript/toolbar/js/es5-getting-started.md
Issues on the getting started documentation resolved.
=> documentation(ES-857792): Issues on the getting started documentation resolved.

ej2-javascript/sidebar/js/getting-started.md, ej2-javascript/treeview/js/es5-getting-started.md
Issues on the getting started documentation resolved.
=> documentation(ES-856562): Issues on the getting started documentation resolved.

ej2-javascript/code-snippet/menu/getting-started-cs3/index.js, ej2-javascript/code-snippet/menu/getting-started-cs3/index.ts
Menu URL link is not loaded properly
Modified the URL link.
Links : 
https://ej2.syncfusion.com/documentation/code-snippet/menu/getting-started-cs3
=> 858328 - Resolved the menu url link issue 

ej2-javascript/code-snippet/stepper/es5-getting-started-cs1/index.ts, ej2-javascript/code-snippet/stepper/es5-getting-started-cs1/js/index.html, ej2-javascript/code-snippet/stepper/es5-iconWithLabel-cs1/index.ts, ej2-javascript/code-snippet/stepper/es5-iconWithLabel-cs1/js/index.html, ej2-javascript/code-snippet/stepper/getting-started-cs1/js/index.html, ej2-javascript/code-snippet/stepper/getting-started-cs1/systemjs.config.js, ej2-javascript/code-snippet/stepper/iconWithLabel/index.ts, ej2-javascript/code-snippet/stepper/iconWithLabel/js/index.html, ej2-javascript/code-snippet/stepper/iconWithLabel/systemjs.config.js
Updated the dependency for stepper as preview sample are not loaded properly.
**Default**
**Icon and Label**
=> documentation(849706): preview sample issue fixed.

ej2-javascript/code-snippet/stepper/es5-getting-started-cs1/index.ts, ej2-javascript/code-snippet/stepper/es5-getting-started-cs1/js/index.html, ej2-javascript/code-snippet/stepper/es5-getting-started-cs1/styles.css, ej2-javascript/code-snippet/stepper/es5-iconWithLabel-cs1/index.ts, ej2-javascript/code-snippet/stepper/es5-iconWithLabel-cs1/js/index.html, ej2-javascript/code-snippet/stepper/es5-iconWithLabel-cs1/styles.css, ej2-javascript/code-snippet/stepper/getting-started-cs1/styles.css, ej2-javascript/code-snippet/stepper/iconWithLabel/styles.css, ej2-javascript/stepper/js/es5-getting-started.md
=> 849706: preview sample issue fixed.

ej2-javascript/breadcrumb/accessibility.md, ej2-javascript/context-menu/accessibility.md, ej2-javascript/menu/accessibility.md
864907: Accessibility sample modification for nav components
=> 864907: Accessibility sample modification for nav components

ej2-javascript/code-snippet/menu/getting-started-cs3/index.js, ej2-javascript/code-snippet/menu/getting-started-cs3/index.ts
858328: Resolved the menu url link issue
=> 858328: Resolved the menu url link issue

ej2-javascript/sidebar/accessibility.md, ej2-javascript/treeview/accessibility.md
Need to update the accessibility UG content for TreeView & Sidebar component.
[865175](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/865175)
NA
NA
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
NA 
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes got approval if UI is added or modified?
Drafted UG …
=> 865175: Updated the accessibility UG content for TreeView & Sidebar.

ej2-javascript/accordion/accessibility.md, ej2-javascript/appbar/accessibility.md, ej2-javascript/carousel/accessibility.md, ej2-javascript/tab/accessibility.md, ej2-javascript/toolbar/accessibility.md
**Description:**
Review correction in accessibility topic in navigation documentation.
=> documentation(ES-864834-reviewCorrection): Review correction in navigation docs.

ej2-javascript/sidebar/ej2-javascript-sidebar-toc.html, ej2-javascript/sidebar/ej2-typescript-sidebar-toc.html
Accessibility UG page were added.
=> 865175: Updated the accessibility UG content for Sidebar component.

ej2-javascript/accordion/accessibility.md, ej2-javascript/appbar/accessibility.md, ej2-javascript/breadcrumb/accessibility.md, ej2-javascript/carousel/accessibility.md, ej2-javascript/context-menu/accessibility.md, ej2-javascript/menu/accessibility.md, ej2-javascript/sidebar/accessibility.md, ej2-javascript/tab/accessibility.md, ej2-javascript/toolbar/accessibility.md, ej2-javascript/treeview/accessibility.md
Need to modified the icons on accessibility document. The Icons are newly created for the compilance measuring.
[866555](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/866555)
NA
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes got approval if UI is …
=> 866555: Need to modified the icons on accessibility document

ej2-javascript/ribbon/ej2-javascript-ribbon-toc.html, ej2-javascript/ribbon/ej2-typescript-ribbon-toc.html, ej2-javascript/ribbon/js/accessibility.md, ej2-javascript/ribbon/ts/accessibility.md
Need to update the Accessibity document for Ribbon.
**Ribbon**
- Accessibility in ##Platform_Name## Ribboncontrol
- WAI-ARIA attributes
- Keyboard interaction
- Ensuring accessibility
- See also
=> documentation(865472): Need to update accessibility document. 

ej2-javascript/code-snippet/ribbon/dropdownCustomization/index.js, ej2-javascript/code-snippet/ribbon/dropdownCustomization/index.ts, ej2-javascript/code-snippet/ribbon/dropdownCustomization/js/index.html, ej2-javascript/code-snippet/ribbon/dropdownCustomization/styles.css, ej2-javascript/code-snippet/ribbon/dropdownCustomization/systemjs.config.js, ej2-javascript/code-snippet/ribbon/dropdownCustomization/ts/index.html, ej2-javascript/ribbon/js/items.md, ej2-javascript/ribbon/ts/items.md
Need to Include a topic about adding a custom class to the Ribbon dropdown items
**Dropdown Item**
=> documentation(866020): Added dropdown items customization.

ej2-javascript/code-snippet/ribbon/dropdownCustomization/index.js, ej2-javascript/code-snippet/ribbon/dropdownCustomization/index.ts, ej2-javascript/code-snippet/ribbon/dropdownCustomization/js/index.html, ej2-javascript/code-snippet/ribbon/dropdownCustomization/styles.css, ej2-javascript/code-snippet/ribbon/dropdownCustomization/systemjs.config.js, ej2-javascript/code-snippet/ribbon/dropdownCustomization/ts/index.html, ej2-javascript/ribbon/js/items.md, ej2-javascript/ribbon/ts/items.md
Need to Include a topic about adding a custom class to the Ribbon dropdown items
**Dropdown Item**
=> documentation(866020): Added dropdown items customization. 

ej2-javascript/stepper/js/accessibility.md, ej2-javascript/stepper/ts/accessibility.md
Need to update the Accessibity document for Stepper.
**Stepper**
- Accessibility in ##Platform_Name## Stepper control
- WAI-ARIA attributes
- Keyboard interaction
- Ensuring accessibility
- See also
=> documentation(865622): Need to update accessibility document

ej2-javascript/treeview/multiple-selection.md
Hi @MallikaRK,
Worked on js treeview changes.
Regards,
Sharly A.
=> SEO-180850-js-treeview-changes
